# Processed E-commerce Dataset
This notebook demonstrates how to process and combine e-commerce datasets using Python and Pandas.
The datasets used in this assignment are:
- Orders
- Customers
- Products
The main tasks include loading the datasets, inspecting the data, merging related DataFrames, demonstrating concat(), creating useful columns using apply(), performing DateTime operations, organizing the final processed dataset, and exporting it as a CSV file.

In [25]:
import pandas as pd

In [26]:
orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products.csv")

## 1. Inspecting the Datasets
First, we will inspect the Orders, Customers, and Products datasets to understand their structure and contents.

In [27]:
print("Orders Dataset:")
display(orders.head(10))

print("Customers Dataset:")
display(customers.head(10))

print("Products Dataset:")
display(products.head(10))

Orders Dataset:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped

Customers Dataset:

  Customer_ID Customer_Name       City Region Membership_Type
0        C001  Aarav Sharma   Srinagar  North         Premium
1        C002     Zoya Khan      Delhi  North         Regular
2        C003   Rohan Mehta     Mumbai   West         Premium
3        C004  Ananya Singh      Jammu  North         Regular
4        C005     Kabir Ali    Lucknow  North             New
5        C006  Ishita Gupta  Bengaluru  South         Premium
6        C007  Aditya Verma       Pune   West         Regular
7        C008    Sara Ahmed  Hyderabad  South         Premium
8        C009    Arjun Nair      Kochi  South         Regular
9        C010    Mehak Bhat   Srinagar  North         Premium

Products Dataset:

  Product_ID         Product_Name        Category  Unit_Price       Brand
0       P001  Wireless Headphones     Electronics        1499    SoundMax
1       P002  Mechanical Keyboard     Electronics        2499      KeyPro
2       P003       Wireless Mouse     Electronics         899    TechGear
3       P004          Smart Watch     Electronics        3299     FitTech
4       P005           Power Bank     Electronics        1199    VoltPlus
5       P006               Hoodie        Clothing        1599   UrbanWear
6       P007               Jacket        Clothing        2499  NorthStyle
7       P008             Sneakers        Clothing        2999      StepUp
8       P009         Coffee Maker  Home & Kitchen        3499    HomeBrew
9       P010      Electric Kettle  Home & Kitchen        1499  KitchenPro

## 2. Merging Orders and Customers
The Orders and Customers datasets are related through the `Customer_ID` column. We will use `merge()` to combine customer information with order details.

In [28]:
orders_customers = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

display(orders_customers.head(10))

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular

## 3. Merging with Products

The merged Orders and Customers DataFrame is now combined with the Products dataset using the `Product_ID` column.

In [29]:
orders_customers_products = pd.merge(
    orders_customers,
    products,
    on="Product_ID",
    how="left"
)

display(orders_customers_products.head(10))

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus

## 4. Demonstrating concat()

The `concat()` function is used to combine DataFrames along an axis. Here, we demonstrate vertical concatenation by combining two subsets of the processed dataset.

In [30]:
part1 = orders_customers_products.iloc[:5]
part2 = orders_customers_products.iloc[5:10]

concat_demo = pd.concat([part1, part2], ignore_index=True)

display(concat_demo)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus

In [31]:
part1 = orders_customers_products.iloc[:5]
part2 = orders_customers_products.iloc[5:10]
concat_demo = pd.concat([part1, part2], ignore_index=True)
display(concat_demo)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus

## 5. Creating a Total Amount Column Using apply()

The `apply()` function is used to create a new `Total_Amount` column by multiplying the quantity of products ordered by their unit price.

In [32]:
orders_customers_products["Total_Amount"] = orders_customers_products.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)

display(orders_customers_products.head(10))

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total_Amount
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,2997
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone,2397
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear,2697
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus,4796
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew,6998
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus,2398

## 6. DateTime Operations

The `Order_Date` column is converted to DateTime format so that date-related information can be extracted easily.

In [33]:
orders_customers_products["Order_Date"] = pd.to_datetime(
    orders_customers_products["Order_Date"]
)

display(orders_customers_products[["Order_Date"]].head(10))

  Order_Date
0 2026-02-19
1 2026-01-25
2 2026-02-26
3 2026-03-04
4 2026-03-29
5 2026-02-09
6 2026-02-10
7 2026-03-27
8 2026-03-13
9 2026-03-05

## 7. Extracting Date Information

After converting the order date to DateTime format, we extract the month, day, and day of the week into separate columns.

In [34]:
orders_customers_products["Order_Month"] = orders_customers_products["Order_Date"].dt.month
orders_customers_products["Order_Day"] = orders_customers_products["Order_Date"].dt.day
orders_customers_products["Order_Day_Name"] = orders_customers_products["Order_Date"].dt.day_name()

display(
    orders_customers_products[
        ["Order_Date", "Order_Month", "Order_Day", "Order_Day_Name"]
    ].head(10)
)

  Order_Date  Order_Month  Order_Day Order_Day_Name
0 2026-02-19            2         19       Thursday
1 2026-01-25            1         25         Sunday
2 2026-02-26            2         26       Thursday
3 2026-03-04            3          4      Wednesday
4 2026-03-29            3         29         Sunday
5 2026-02-09            2          9         Monday
6 2026-02-10            2         10        Tuesday
7 2026-03-27            3         27         Friday
8 2026-03-13            3         13         Friday
9 2026-03-05            3          5       Thursday

## 8. Organizing the Final Processed Dataset

The columns are arranged in a logical order to create a clean and meaningful processed dataset.

In [35]:
final_df = orders_customers_products[
    [
        "Order_ID",
        "Order_Date",
        "Order_Month",
        "Order_Day",
        "Order_Day_Name",
        "Customer_ID",
        "Customer_Name",
        "City",
        "Region",
        "Membership_Type",
        "Product_ID",
        "Product_Name",
        "Category",
        "Brand",
        "Unit_Price",
        "Quantity",
        "Total_Amount",
        "Payment_Method",
        "Order_Status"
    ]
]

display(final_df.head(10))

,Order_ID,Order_Date,Order_Month,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,Region,Membership_Type,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Total_Amount,Payment_Method,Order_Status
0,O0001,2026-02-19,2,19,Thursday,C027,Harsh Vardhan,Noida,North,Premium,P019,Cricket Bat,Sports,BatPro,2499,2,4998,Credit Card,Delivered
1,O0002,2026-01-25,1,25,Sunday,C006,Ishita Gupta,Bengaluru,South,Premium,P003,Wireless Mouse,Electronics,TechGear,899,2,1798,Debit Card,Delivered
2,O0003,2026-02-26,2,26,Thursday,C015,Karan Joshi,Chandigarh,North,Regular,P004,Smart Watch,Electronics,FitTech,3299,1,3299,Cash on Delivery,Delivered
3,O0004,2026-03-04,3,4,Wednesday,C024,Maryam Khan,Hyderabad,South,Regular,P015,Machine Learning Basics,Books,AIPress,999,3,2997,Net Banking,Delivered
4,O0005,2026-03-29,3,29,Sunday,C025,Reyansh Jain,Kolkata,East,New,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,5,17495,Credit Card,Delivered
5,O0006,2026-02-09,2,9,Monday,C003,Rohan Mehta,Mumbai,West,Premium,P018,Football,Sports,SportZone,799,3,2397,UPI,Delivered
6,O0007,2026-02-10,2,10,Tuesday,C011,Vivaan Kapoor,Jaipur,North,New,P003,Wireless Mouse,Electronics,TechGear,899,3,2697,UPI,Delivered
7,O0008,2026-03-27,3,27,Friday,C020,Priya Menon,Chennai,South,Premium,P005,Power Bank,Electronics,VoltPlus,1199,4,4796,Debit Card,Delivered
8,O0009,2026-03-13,3,13,Friday,C024,Maryam Khan,Hyderabad,South,Regular,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,2,6998,UPI,Cancelled
9,O0010,2026-03-05,3,5,Thursday,C026,Fatima Noor,Srinagar,North,Regular,P005,Power Bank,Electronics,VoltPlus,1199,2,2398,Debit Card,Shipped

## 9. Exporting the Processed Dataset

The final processed DataFrame is exported as a CSV file so that it can be used for further analysis and uploaded to GitHub.

In [36]:
final_df.to_csv("Day9_Processed_Ecommerce_Dataset.csv", index=False)

print("Processed dataset exported successfully.")

Processed dataset exported successfully.

## 10. Conclusion

The Orders, Customers, and Products datasets were successfully loaded and processed using Pandas. The related datasets were combined using `merge()`, and `concat()` was demonstrated for combining DataFrames. A `Total_Amount` column was created using `apply()`. DateTime operations were performed on the order dates to extract the month, day, and day of the week. Finally, the data was organized into a clean processed DataFrame and exported as `Day9_Processed_Ecommerce_Dataset.csv`.